Imported updates of existing bootscripts
Imported bootscripts that already existed from clfs-embedded/bootscripts
as bootscripts should be kept in this repo rather than in the
clfs-embedded repo.

The script changes have NOT BEEN TESTED! (yet)
This is part of a cleanup of bootscripts.

diff --git a/clfs/rc.d/startup b/clfs/rc.d/startup
--- a/clfs/rc.d/startup
+++ b/clfs/rc.d/startup
@@ -6,58 +6,57 @@
 
 /bin/mount -t proc none /proc
 /bin/mount -t sysfs none /sys
+/bin/mount -t tmpfs /tmp /tmp
 /bin/mount -t tmpfs -o mode=0755 none /dev
 /bin/mkdir /dev/pts
 /bin/mkdir /dev/shm
+/bin/mount -t tmpfs -o mode=0755 /var /var
+for x in cache lib lib/misc lib/locate local lock log mail opt run spool; do mkdir /var/$x; done
+ln -s ../tmp /var/tmp
+
 /bin/echo "/sbin/mdev" > /proc/sys/kernel/hotplug
+
+echo -n "Starting mdev: "
 /sbin/mdev -s
-
-echo -n "Setting system clock: "
-hwclock --hctosys --utc
-check_status
-
-echo "Starting fsck for root filesystem."
-fsck -T -C /
-if [ "$?" -gt 2 ]; then
-  echo "WARNING: Errors found while checking root filesystem."
-  echo "You can login as root now, the system will reboot after logout."
-  sulogin
-  reboot
-elif [ "$?" = "2" ]; then
-  echo "NOTICE: System needs to be rebooted now."
-  sleep 1
-  reboot
-else
-  echo -n "Checking root filesystem: "
-  check_status
-fi
-
-echo -n "Remounting root rw: "
-mount -o remount,rw /
 check_status
 
 echo -n "Mounting devpts: "
 mount /dev/pts
 check_status
 
-echo "Starting fsck for local filesystems."
-fsck -A -C -R -T -t nonfs,nosmbfs
-if [ "$?" -gt 2 ]; then
-  echo "WARNING: Errors found while checking filesystems."
-  echo "You can login as root now, the system will reboot after logout."
-  sulogin
-  reboot
-elif [ "$?" = "2" ]; then
-  echo "NOTICE: System needs to be rebooted now."
-  sleep 1
-  reboot
-else
-  echo -n "Checking local filesystems: "
-  check_status
+if [ -x /sbin/hwclock ] && [ -e /dev/rtc ]; then
+	echo -n "Setting system clock: "
+	hwclock --hctosys --utc
+	check_status
 fi
 
-echo -n "Enabling swap space: "
-swapon -a
+if [ -x /sbin/fsck ]; then
+	echo "Starting fsck for local filesystems."
+	fsck -A -C -R -T -t nonfs,nosmbfs
+	if [ "$?" -gt 2 ]; then
+		echo "WARNING: Errors found while checking filesystems."
+		echo "You can login as root now, the system will reboot after logout."
+		sulogin
+		reboot
+	elif [ "$?" = "2" ]; then
+		echo "NOTICE: System needs to be rebooted now."
+		sleep 1
+		reboot
+	else
+		echo -n "Checking local filesystems: "
+		check_status
+	fi
+fi
+
+
+if [ -x /sbin/swapon ]; then
+	echo -n "Enabling swap space: "
+	swapon -a
+	check_status
+fi
+
+echo -n "Remounting root rw: "
+mount -o remount,rw /
 check_status
 
 echo -n "Setting hostname: "
@@ -81,8 +80,11 @@ check_status
 
 echo "Running start scripts."
 
-for i in /etc/rc.d/start/*; do
-  if [ -x $i ]; then
-    $i start
-  fi
+for i in /etc/rc.d/start/*
+do
+	if [ -x $i ]; then
+		$i start
+	fi
 done
+
+exit 0
