Formatting change to embedded

diff --git a/clfs/rc.d/init.d/functions b/clfs/rc.d/init.d/functions
--- a/clfs/rc.d/init.d/functions
+++ b/clfs/rc.d/init.d/functions
@@ -10,12 +10,12 @@ PATH=/bin:/sbin:/usr/bin:/usr/sbin
 #
 check_status()
 {
-	local ERR=$?
-	echo -en "\\033[65G"
-	if [ $ERR = 0 ]; then
-		echo -en "\\033[1;32mOK"
-	else
-		echo -en "\\033[1;31mFAIL"
-	fi
-	echo -e "\\033[0;39m"
+  local ERR=$?
+  echo -en "\\033[65G"
+  if [ $ERR = 0 ]; then
+    echo -en "\\033[1;32mOK"
+  else
+    echo -en "\\033[1;31mFAIL"
+  fi
+  echo -e "\\033[0;39m"
 }
